// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // promo_code: 1a2b3c4d5e6f
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyN98gveTYPlOOZkWfpCtneMGTEka9yx4',
    appId: '1:769415739370:web:1c96291fce463e47c1a493',
    messagingSenderId: '769415739370',
    projectId: 'smartnotetdm',
    authDomain: 'smartnotetdm.firebaseapp.com',
    storageBucket: 'smartnotetdm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA_JO7xbZZpaYvU9bR_t2iYIb5g_08GCs',
    appId: '1:769415739370:android:b3aa88fbc3753862c1a493',
    messagingSenderId: '769415739370',
    projectId: 'smartnotetdm',
    storageBucket: 'smartnotetdm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc0HFOkfMaGMxlIEiaOIq0a8WWBlcktBk',
    appId: '1:769415739370:ios:29c9c47e5c249df3c1a493',
    messagingSenderId: '769415739370',
    projectId: 'smartnotetdm',
    storageBucket: 'smartnotetdm.firebasestorage.app',
    iosBundleId: 'com.example.smartnote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc0HFOkfMaGMxlIEiaOIq0a8WWBlcktBk',
    appId: '1:769415739370:ios:29c9c47e5c249df3c1a493',
    messagingSenderId: '769415739370',
    projectId: 'smartnotetdm',
    storageBucket: 'smartnotetdm.firebasestorage.app',
    iosBundleId: 'com.example.smartnote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyN98gveTYPlOOZkWfpCtneMGTEka9yx4',
    appId: '1:769415739370:web:0fafebe6e6d37515c1a493',
    messagingSenderId: '769415739370',
    projectId: 'smartnotetdm',
    authDomain: 'smartnotetdm.firebaseapp.com',
    storageBucket: 'smartnotetdm.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'YOUR_LINUX_API_KEY',
    appId: 'YOUR_LINUX_APP_ID',
    messagingSenderId: 'YOUR_LINUX_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    databaseURL: 'YOUR_DATABASE_URL',
    storageBucket: 'YOUR_STORAGE_BUCKET',
  );
}