// File generated by the FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions.currentPlatform is not supported on this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdcehWPxotAYfJB5jOn2dH4MCsbnz12_c',
    appId: '1:797318087218:android:d021051999da29274bb22b',
    messagingSenderId: '797318087218',
    projectId: 'menumonan',
    storageBucket: 'menumonan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKY5dRQmFYRBsOc2dxN7w9uP5fK6cJ8_h',
    appId: '1:797318087218:ios:d021051999da29274bb22b',
    messagingSenderId: '797318087218',
    projectId: 'menumonan',
    storageBucket: 'menumonan.firebasestorage.app',
    iosBundleId: 'com.example.menumonan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKY5dRQmFYRBsOc2dxN7w9uP5fK6cJ8_h',
    appId: '1:797318087218:macos:d021051999da29274bb22b',
    messagingSenderId: '797318087218',
    projectId: 'menumonan',
    storageBucket: 'menumonan.firebasestorage.app',
    iosBundleId: 'com.example.menumonan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdcehWPxotAYfJB5jOn2dH4MCsbnz12_c',
    appId: '1:797318087218:windows:d021051999da29274bb22b',
    messagingSenderId: '797318087218',
    projectId: 'menumonan',
    storageBucket: 'menumonan.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAdcehWPxotAYfJB5jOn2dH4MCsbnz12_c',
    appId: '1:797318087218:linux:d021051999da29274bb22b',
    messagingSenderId: '797318087218',
    projectId: 'menumonan',
    storageBucket: 'menumonan.firebasestorage.app',
  );
}
